---
apiVersion: v1
kind: Namespace
metadata:
  name: sysdig-image-scan
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysdig-image-scan
  namespace: sysdig-image-scan
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: image-scan-config
  namespace: sysdig-image-scan
data:
  SYSDIG_SECURE_URL: https://api.sysdigcloud.com/api/scanning/v1/anchore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sysdig-image-scan
  name: sysdig-image-scan
  namespace: sysdig-image-scan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sysdig-image-scan
  template:
    metadata:
      labels:
        app: sysdig-image-scan
    spec:
      serviceAccount: sysdig-image-scan
      containers:
      - image: sysdiglabs/opa-image-scanner
        name: image-scan-webhook
        args:
          - --secure-port=8443
          - --tls-cert-file
          - /cert/tls.crt
          - --tls-private-key-file
          - /cert/tls.key
        envFrom:
          - configMapRef:
              name: image-scan-config
          - secretRef:
              name: sysdig-secure-token
        volumeMounts:
          - name: cert
            mountPath: /cert
            readOnly: true
          - name: rules
            mountPath: /tmp/image-scan
            readOnly: true
      volumes:
      - name: cert
        secret:
          secretName: sysdig-image-scan-tls
      - name: rules
        configMap:
          name: image-scan-rules
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sysdig-image-scan
  name: image-scan-webhook
  namespace: sysdig-image-scan
spec:
  ports:
  - name: webhook-port
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: sysdig-image-scan
  sessionAffinity: None
  type: ClusterIP
---  