apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sysdig-image-scanner.name" . }}-post-scan-rules
  labels:
    {{ include "sysdig-image-scanner.labels" . | nindent 4 }}
data:
  post-scan-rules.rego: |
        package imageadmission
        # Helper variables
        namespace := input.AdmissionRequest.namespace
        policies := data.policies

{{ if .Values.scanPolicies.autoGenerate }}
        {{- $common := .Files.Get "commonrules.rego"}}
        {{- if eq $common "" }}{{ fail "commonrules.rego file was not found"}}{{ end }}
        {{- $rules := .Files.Get "postscanrules.rego"}}
        {{- if eq $rules "" }}{{ fail "postscanrules.rego file was not found"}}{{ end }}
        {{- $common | indent 8}}
        {{- $rules | indent 8}}
{{ end }}
        ###### Begin: Custom rules ######
{{ .Values.customRules | indent 8 -}}
        ###### End: Custom rules ######
