apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sysdig-image-scanner.name" . }}-rules
  labels:
    {{ include "sysdig-image-scanner.labels" . | nindent 4 }}
data:
  rules.rego: |
        package imageadmission
        # Helper variables
        policies := data.policies
        namespace := input.AdmissionRequest.namespace

{{ if .Values.scanPolicies.autoGenerate }}
        {{- $rules := .Files.Get "imageadmission.rego"}}
        {{- if eq $rules "" }}{{ fail "imageadmission.rego file was not found"}}{{ end }}
        {{- $rules | indent 8}}
{{ end }}
        ###### Begin: Custom rules ######
{{ .Values.customRules | indent 8 -}}
        ###### End: Custom rules ######
